name: Open Release

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  open_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2

      - name: Instalar jq
        run: sudo apt-get install jq  # Instala jq para manipulação de JSON

      - name: Executar script.sh
        run: |
          chmod +x script.sh  # Garante que o script seja executável
          ./script.sh          # Executa o script
        env:
          PAT_TOKEN: ${{ secrets.REPO_TOKEN }}  # Passa o token como variável de ambiente
