name: Open Release

on:
  workflow_dispatch:  # Permite execução manual

permissions:
  contents: write     # Permissão de escrita
  pages: write        # Permissão para páginas
  id-token: write

jobs:
  open_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2

      - name: Instalar jq
        run: sudo apt-get install jq  # Instala jq para manipulação de JSON

      - name: Executar script.sh
        run: |
          chmod +x script.sh  # Garante que o script seja executável
          ./script.sh          # Executa o script
        env:
          PAT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAT_REPO: ${{github.repository}}
